#!/bin/bash
python trajectory_routine.py force 20
python trajectory_routine.py force 30
python trajectory_routine.py force 40
python trajectory_routine.py force 50
python trajectory_routine.py force 60
python trajectory_routine.py force 70
python trajectory_routine.py force 80
python trajectory_routine.py force 90
python trajectory_routine.py force 100
python trajectory_routine.py force 110
python trajectory_routine.py force 120
python trajectory_routine.py force 130
python trajectory_routine.py force 140
python trajectory_routine.py force 150
python trajectory_routine.py force 160
python trajectory_routine.py force 170
python trajectory_routine.py force 180

python trajectory_routine.py grid 20
python trajectory_routine.py grid 30
python trajectory_routine.py grid 40
python trajectory_routine.py grid 50
python trajectory_routine.py grid 60
python trajectory_routine.py grid 70
python trajectory_routine.py grid 80
python trajectory_routine.py grid 90
python trajectory_routine.py grid 100
python trajectory_routine.py grid 110
python trajectory_routine.py grid 120
python trajectory_routine.py grid 130
python trajectory_routine.py grid 140
python trajectory_routine.py grid 150
python trajectory_routine.py grid 160
python trajectory_routine.py grid 170
python trajectory_routine.py grid 180